import { defineType, defineField, defineArrayMember } from 'sanity'

export default defineType({
  name: 'homePage',
  title: 'Home Page',
  type: 'document',
  // Desk structure should use S.documentTypeListItem('homePage').id('homePage') for this singleton
  fieldsets: [
    { name: 'hero', title: 'Hero Section' },
    { name: 'intro', title: 'Intro Section' },
    { name: 'whyUs', title: 'Why Us Section' },
    { name: 'reviews', title: 'Reviews Section' },
    { name: 'locations', title: 'Locations Section' },
    { name: 'cta', title: 'CTA Section' },
    { name: 'seo', title: 'SEO Settings' },
  ],
  fields: [
    defineField({
      name: 'hero_badge',
      title: 'Hero Badge',
      type: 'string',
      description: 'e.g. "4.9★ Google · 115 reviews"',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_certBadge',
      title: 'Hero Cert Badge',
      type: 'string',
      description: 'e.g. "Certified Invisalign focus"',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_heading',
      title: 'Hero Heading',
      type: 'string',
      description: 'Main headline displayed in the hero section',
      validation: Rule => Rule.required(),
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_subheading',
      title: 'Hero Subheading',
      type: 'string',
      description: 'Secondary line below the main heading',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_description',
      title: 'Hero Description',
      type: 'text',
      description: 'Supporting paragraph in the hero section',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_ctaPrimary_label',
      title: 'Primary CTA Label',
      type: 'string',
      description: 'Text for the main call-to-action button',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_ctaPrimary_url',
      title: 'Primary CTA URL',
      type: 'string',
      description: 'Link for the main call-to-action button',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_ctaSecondary_label',
      title: 'Secondary CTA Label',
      type: 'string',
      description: 'Text for the secondary call-to-action button',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_ctaSecondary_url',
      title: 'Secondary CTA URL',
      type: 'string',
      description: 'Link for the secondary call-to-action button',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_hoursNote',
      title: 'Hours Note',
      type: 'string',
      description: 'e.g. "Mon–Sat · 10:00 AM – 8:00 PM"',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_backgroundImage',
      title: 'Hero Background Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Full-width background image for the hero',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_inlineImage',
      title: 'Hero Inline Image',
      type: 'image',
      options: { hotspot: true },
      description: 'Foreground or inline image in the hero layout',
      fieldset: 'hero',
    }),
    defineField({
      name: 'intro_sectionLabel',
      title: 'Section Label',
      type: 'string',
      description: 'e.g. "Your dental home"',
      fieldset: 'intro',
    }),
    defineField({
      name: 'intro_heading',
      title: 'Heading',
      type: 'string',
      description: 'Headline for the intro section',
      fieldset: 'intro',
    }),
    defineField({
      name: 'intro_body',
      title: 'Body',
      type: 'text',
      description: 'Introductory copy for the section',
      fieldset: 'intro',
    }),
    defineField({
      name: 'intro_bullets',
      title: 'Bullets',
      type: 'array',
      description: 'Short bullet points highlighting key benefits',
      of: [defineArrayMember({ type: 'string' })],
      fieldset: 'intro',
    }),
    defineField({
      name: 'intro_ctaLabel',
      title: 'CTA Label',
      type: 'string',
      description: 'Text for the intro section call-to-action',
      fieldset: 'intro',
    }),
    defineField({
      name: 'intro_ctaUrl',
      title: 'CTA URL',
      type: 'string',
      description: 'Link for the intro section call-to-action',
      fieldset: 'intro',
    }),
    defineField({
      name: 'intro_image1',
      title: 'Image 1',
      type: 'image',
      options: { hotspot: true },
      description: 'First image in the intro image pair',
      fieldset: 'intro',
    }),
    defineField({
      name: 'intro_image2',
      title: 'Image 2',
      type: 'image',
      options: { hotspot: true },
      description: 'Second image in the intro image pair',
      fieldset: 'intro',
    }),
    defineField({
      name: 'intro_trustNote',
      title: 'Trust Note',
      type: 'string',
      description: 'Small trust line displayed below the images',
      fieldset: 'intro',
    }),
    defineField({
      name: 'whyUs_sectionLabel',
      title: 'Section Label',
      type: 'string',
      description: 'e.g. "Why Mangaluru patients stay"',
      fieldset: 'whyUs',
    }),
    defineField({
      name: 'whyUs_heading',
      title: 'Heading',
      type: 'string',
      description: 'Headline for the Why Us section',
      fieldset: 'whyUs',
    }),
    defineField({
      name: 'whyUs_ctaLabel',
      title: 'CTA Label',
      type: 'string',
      description: 'Text for the Why Us call-to-action',
      fieldset: 'whyUs',
    }),
    defineField({
      name: 'whyUs_ctaUrl',
      title: 'CTA URL',
      type: 'string',
      description: 'Link for the Why Us call-to-action',
      fieldset: 'whyUs',
    }),
    defineField({
      name: 'whyUs_cards',
      title: 'Cards',
      type: 'array',
      description: 'Feature cards explaining why patients choose the clinic',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              description: 'Card heading',
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'text',
              description: 'Card body copy',
            }),
          ],
        }),
      ],
      fieldset: 'whyUs',
    }),
    defineField({
      name: 'reviews_sectionLabel',
      title: 'Section Label',
      type: 'string',
      description: 'e.g. "Wall of love"',
      fieldset: 'reviews',
    }),
    defineField({
      name: 'reviews_heading',
      title: 'Heading',
      type: 'string',
      description: 'Headline for the reviews section',
      fieldset: 'reviews',
    }),
    defineField({
      name: 'reviews_subheading',
      title: 'Subheading',
      type: 'text',
      description: 'Supporting text above the review cards',
      fieldset: 'reviews',
    }),
    defineField({
      name: 'reviews_items',
      title: 'Review Items',
      type: 'array',
      description: 'Patient testimonials displayed in the wall of love',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({
              name: 'quote',
              title: 'Quote',
              type: 'text',
              description: 'The patient review text',
            }),
            defineField({
              name: 'reviewerLabel',
              title: 'Reviewer Label',
              type: 'string',
              description: 'e.g. "Google reviewer" or patient name',
            }),
            defineField({
              name: 'platform',
              title: 'Platform',
              type: 'string',
              description: 'e.g. "Google", "Facebook"',
            }),
          ],
        }),
      ],
      fieldset: 'reviews',
    }),
    defineField({
      name: 'locations_sectionLabel',
      title: 'Section Label',
      type: 'string',
      description: 'Small label above the locations heading',
      fieldset: 'locations',
    }),
    defineField({
      name: 'locations_heading',
      title: 'Heading',
      type: 'string',
      description: 'Headline for the locations section',
      fieldset: 'locations',
    }),
    defineField({
      name: 'locations_subheading',
      title: 'Subheading',
      type: 'text',
      description: 'Supporting text for the locations section',
      fieldset: 'locations',
    }),
    defineField({
      name: 'cta_sectionLabel',
      title: 'Section Label',
      type: 'string',
      description: 'Small label above the bottom CTA heading',
      fieldset: 'cta',
    }),
    defineField({
      name: 'cta_heading',
      title: 'Heading',
      type: 'string',
      description: 'Headline for the bottom call-to-action section',
      fieldset: 'cta',
    }),
    defineField({
      name: 'cta_hoursNote',
      title: 'Hours Note',
      type: 'string',
      description: 'Clinic hours shown in the CTA section',
      fieldset: 'cta',
    }),
    defineField({
      name: 'cta_primaryLabel',
      title: 'Primary CTA Label',
      type: 'string',
      description: 'Text for the main booking button',
      fieldset: 'cta',
    }),
    defineField({
      name: 'cta_primaryUrl',
      title: 'Primary CTA URL',
      type: 'string',
      description: 'Link for the main booking button',
      fieldset: 'cta',
    }),
    defineField({
      name: 'cta_whatsappLabel',
      title: 'WhatsApp Label',
      type: 'string',
      description: 'Text for the WhatsApp button',
      fieldset: 'cta',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'pageSeo',
      description: 'Page-specific SEO overrides',
      fieldset: 'seo',
    }),
  ],
})
