import { defineType, defineField, defineArrayMember } from 'sanity'

export default defineType({
  name: 'servicesPage',
  title: 'Services Page',
  type: 'document',
  // Desk structure should use S.documentTypeListItem('servicesPage').id('servicesPage') for this singleton
  fieldsets: [
    { name: 'hero', title: 'Hero Section' },
    { name: 'categories', title: 'Service Categories' },
    { name: 'invisalign', title: 'Invisalign Section' },
    { name: 'serviceDirectory', title: 'Service Directory' },
    { name: 'seo', title: 'SEO Settings' },
  ],
  fields: [
    defineField({
      name: '__experimental_actions',
      type: 'string',
      hidden: true,
    }),
    defineField({
      name: 'hero_sectionLabel',
      title: 'Section Label',
      type: 'string',
      description: 'Small label above the hero heading',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_heading',
      title: 'Heading',
      type: 'string',
      description: 'Main headline for the Services page',
      validation: Rule => Rule.required(),
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_subheading',
      title: 'Subheading',
      type: 'text',
      description: 'Supporting text below the hero heading',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_ctaLabel',
      title: 'CTA Label',
      type: 'string',
      description: 'Text for the hero call-to-action button',
      fieldset: 'hero',
    }),
    defineField({
      name: 'hero_ctaUrl',
      title: 'CTA URL',
      type: 'string',
      description: 'Link for the hero call-to-action button',
      fieldset: 'hero',
    }),
    defineField({
      name: 'categories',
      title: 'Categories',
      type: 'array',
      description: 'Grouped service categories with icons',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({
              name: 'title',
              title: 'Title',
              type: 'string',
              description: 'Category name',
            }),
            defineField({
              name: 'description',
              title: 'Description',
              type: 'text',
              description: 'Short summary of this category',
            }),
            defineField({
              name: 'icon',
              title: 'Icon',
              type: 'image',
              options: { hotspot: true },
              description: 'Icon or image representing this category',
            }),
          ],
        }),
      ],
      fieldset: 'categories',
    }),
    defineField({
      name: 'invisalign_heading',
      title: 'Invisalign Heading',
      type: 'string',
      description: 'Headline for the Invisalign spotlight section',
      fieldset: 'invisalign',
    }),
    defineField({
      name: 'invisalign_subheading',
      title: 'Invisalign Subheading',
      type: 'string',
      description: 'Supporting line below the Invisalign heading',
      fieldset: 'invisalign',
    }),
    defineField({
      name: 'invisalign_body',
      title: 'Invisalign Body',
      type: 'text',
      description: 'Detailed copy about Invisalign treatment',
      fieldset: 'invisalign',
    }),
    defineField({
      name: 'invisalign_logo',
      title: 'Invisalign Logo',
      type: 'image',
      options: { hotspot: true },
      description: 'Invisalign brand logo',
      fieldset: 'invisalign',
    }),
    defineField({
      name: 'directory_heading',
      title: 'Directory Heading',
      type: 'string',
      description: 'Headline for the full service list',
      fieldset: 'serviceDirectory',
    }),
    defineField({
      name: 'directory_note',
      title: 'Directory Note',
      type: 'text',
      description: 'Optional note displayed above the service list',
      fieldset: 'serviceDirectory',
    }),
    defineField({
      name: 'directory_items',
      title: 'Directory Items',
      type: 'array',
      description: 'List of all services (rendered as checkmarks on the frontend)',
      of: [defineArrayMember({ type: 'string' })],
      fieldset: 'serviceDirectory',
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'pageSeo',
      description: 'Page-specific SEO overrides',
      fieldset: 'seo',
    }),
  ],
})
